version: "3"
services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.tests
    container_name: test-runner
    environment:
      SONATYPE_USER: ${SONATYPE_USER}
      SONATYPE_PASSWORD: ${SONATYPE_PASSWORD}
    volumes:
      - ~/.m2/repository:/root/.m2/repository
    command: ["mvn", "test"]
