
varnish:
  shortName: "semanticReaderVarnish"
  path: content/
  jerseyClient:
      timeout: 4000ms
  primaryNodes: ["localhost:9090:9091"]
  secondaryNodes: null

pipeline:
  webUrlTemplates:
    "http://www.ft.com/ontology/origin/FTComMethode" : "http://www.ft.com/cms/s/{{originatingIdentifier}}.html"
    "http://www.ft.com/ontology/origin/FT-CLAMO"  : "http://www.ft.com/fastft?post={{originatingIdentifier}}"
    "http://www.ft.com/ontology/origin/FT-LABS-WP-1-[0-9]+" : "{{originatingIdentifier}}"
    "http://api.ft.com/system/FTCOM-METHODE" : "http://www.ft.com/cms/s/{{originatingIdentifier}}.html"
    "http://api.ft.com/system/FT-CLAMO"  : "http://www.ft.com/fastft?post={{originatingIdentifier}}"
    "http://api.ft.com/system/FT-LABS-WP-1-[0-9]+" : "{{originatingIdentifier}}"


policyBrandsMapper:
  policyFilterParameterList:
       - policy: FASTFT_CONTENT_ONLY
         forBrand:
                  - http://api.ft.com/things/5c7592a8-1f0c-11e4-b0cb-b2227cce2b54
       - policy: EXCLUDE_FASTFT_CONTENT
         notForBrand:
                  - http://api.ft.com/things/5c7592a8-1f0c-11e4-b0cb-b2227cce2b54
       - policy: ALPHAVILLE_CONTENT_ONLY
         forBrand:
                  - http://api.ft.com/things/89d15f70-640d-11e4-9803-0800200c9a66
       - policy: EXCLUDE_ALPHAVILLE_CONTENT
         notForBrand:
                  - http://api.ft.com/things/89d15f70-640d-11e4-9803-0800200c9a66
       - policy: BLOG_CONTENT_ONLY
         forBrand:
                  - http://api.ft.com/things/89d15f70-640d-11e4-9803-0800200c9a66
                  - http://api.ft.com/things/3a37a89e-14ce-4ac8-af12-961a9630dce3
       - policy: EXCLUDE_BLOG_CONTENT
         notForBrand:
                  - http://api.ft.com/things/89d15f70-640d-11e4-9803-0800200c9a66
                  - http://api.ft.com/things/3a37a89e-14ce-4ac8-af12-961a9630dce3

server:

  applicationConnectors:
      - type: http
        port: 20080

  adminConnectors:
      - type: http
        port: 20082

  requestLog:

    appenders:

      - type: console
        logFormat: "%-5p [%d{ISO8601, GMT}] %c: %X{transaction_id} %m [%thread]%n%xEx"

        # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
        timeZone: UTC

      - type: file

        # The file to which current statements will be logged.
        currentLogFilename: /var/log/apps/api-policy-component-dw-access.log
        logFormat: "%-5p [%d{ISO8601, GMT}] %c: %X{transaction_id} %m [%thread]%n%xEx"

        # When the log file rotates, the archived log will be renamed to this and gzipped. The
        # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
        # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
        archivedLogFilenamePattern: /var/log/apps/api-policy-component-dw-access-%d.log.gz

        # The number of archived files to keep.
        archivedFileCount: 6

        # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
        timeZone: UTC

logging:

  level: INFO

  loggers:
    io.dropwizard: DEBUG

  appenders:

    - type: console
      logFormat: "%-5p [%d{ISO8601, GMT}] %c: %X{transaction_id} %m [%thread]%n%xEx"

    - type: file
      logFormat: "%-5p [%d{ISO8601, GMT}] %c: %X{transaction_id} %m [%thread]%n%xEx"
      # Do not write log statements below this threshold to the file.
      threshold: ALL

      # The file to which current statements will be logged.
      currentLogFilename: /var/log/apps/api-policy-component-dw-app.log

      # When the log file rotates, the archived log will be renamed to this and gzipped. The
      # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
      # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
      archivedLogFilenamePattern: /var/log/apps/api-policy-component-dw-app-%d.log.gz

      # The number of archived files to keep.
      archivedFileCount: 5

      # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
      timeZone: UTC
