
varnish:
  shortName: "semanticReaderVarnish"
  path: content/
  jerseyClient:
      timeout: 2000ms
  primaryNodes: ["localhost:9090:9091"]
  secondaryNodes: null

pipeline:
  webUrlTemplates:
    "http://www.ft.com/ontology/origin/FTComMethode" : "http://www.ft.com/cms/s/{{originatingIdentifier}}.html"
    "http://www.ft.com/ontology/origin/FT-CLAMO"  : "http://www.ft.com/fastft/{{originatingIdentifier}}"



slowRequestPattern: '*.html'
slowRequestTimeout: 1000  #1 second

server:

  applicationConnectors:
    - type: http
      port: 20080

  adminConnectors:
      - type: http
        port: 20082

  requestLog:

    appenders:

      - type: console
        logFormat: "%-5p [%d{ISO8601, GMT}] %c: %X{transaction_id} %m [%thread]%n%xEx"

        # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
        timeZone: UTC

      - type: file

        # The file to which current statements will be logged.
        currentLogFilename: /var/log/apps/policy-component-dw-access.log
        logFormat: "%-5p [%d{ISO8601, GMT}] %c: %X{transaction_id} %m [%thread]%n%xEx"

        # When the log file rotates, the archived log will be renamed to this and gzipped. The
        # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
        # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
        archivedLogFilenamePattern: /var/log/apps/policy-component-dw-access-%d.log.gz

        # The number of archived files to keep.
        archivedFileCount: 6

        # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
        timeZone: UTC

logging:

  level: INFO

  loggers:
    io.dropwizard: DEBUG

  appenders:

    - type: console
      logFormat: "%-5p [%d{ISO8601, GMT}] %c: %X{transaction_id} %m [%thread]%n%xEx"

    - type: file
      logFormat: "%-5p [%d{ISO8601, GMT}] %c: %X{transaction_id} %m [%thread]%n%xEx"
      # Do not write log statements below this threshold to the file.
      threshold: ALL

      # The file to which current statements will be logged.
      currentLogFilename: /var/log/apps/policy-component-dw-app.log

      # When the log file rotates, the archived log will be renamed to this and gzipped. The
      # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
      # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
      archivedLogFilenamePattern: /var/log/apps/policy-component-dw-app-%d.log.gz

      # The number of archived files to keep.
      archivedFileCount: 5

      # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
      timeZone: UTC
