version: 2
jobs:
  build:
    working_directory: ~/api-policy-component
    docker:
      - image: maven:3.5.0
    steps:
      - checkout
      - run:
          name: Maven integration Tests
          command: mvn integration-test
  dockerfile:
    working_directory: ~/api-policy-component
    docker:
      - image: docker:18.03
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build Dockerfile
          command: docker build .
workflows:
  version: 2
  test-and-build-docker:
    jobs:
      - build
      - dockerfile:
          requires:
            - build
  erseyRequestForwarderTest.java