version: 2
workflows:
  version: 2
  build-docker-image:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Build package, run tests and upload test coverage
          command: |
            mkdir -p ~/.m2/
            curl -v -o ~/.m2/settings.xml "https://raw.githubusercontent.com/Financial-Times/nexus-settings/master/public-settings.xml"
            mvn clean package jacoco:report-aggregate coveralls:report -Djava.net.preferIPv4Stack=true -DrepoToken=${COVERALLS_TOKEN}
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Set Docker image tag based on branch or git tag
          command: |
            if [ ! -z "${CIRCLE_TAG}" ] ; then
              echo 'export DOCKER_TAG=${CIRCLE_TAG}' >> $BASH_ENV
            elif [ "${CIRCLE_BRANCH}" == "master" ] ; then
              echo 'export DOCKER_TAG=latest' >> $BASH_ENV
            else
              echo 'export DOCKER_TAG=$( echo ${CIRCLE_BRANCH} | cut -f 2 -d / )' >> $BASH_ENV
            fi
      - run:
          name: Build Docker image
          command: |
            source ${BASH_ENV}
            docker build \
            --build-arg SONATYPE_USER=${SONATYPE_USER} \
            --build-arg SONATYPE_PASSWORD=${SONATYPE_PASSWORD} \
            --build-arg GIT_TAG=${DOCKER_TAG} \
            --tag nexus.in.ft.com:5000/coco/${CIRCLE_PROJECT_REPONAME}:${DOCKER_TAG} .
