apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.service.name }} 
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}" 
    visualize: "true" 
    app: {{ .Values.service.name }} 
spec:
  replicas: {{ .Values.replicaCount }} 
  selector: 
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        visualize: "true" 
    spec:
      containers: 
      - name: {{ .Chart.Name }} 
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}" 
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env: 
        - name: JAVA_OPTS
          value: "-Xms384m -Xmx384m -XX:+UseG1GC -server"
        - name: CHECKING_VULCAN_HEALTH
          value: "false"
        - name: GRAPHITE_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.host
        - name: GRAPHITE_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.port
        - name: READ_ENDPOINT
          value: "path-routing-varnish:80"
        - name: JERSEY_TIMEOUT_DURATION
          value: "10000ms"
        - name: GRAPHITE_PREFIX
          value: 'coco.services.{{required "The target_env value is required for this app. Use helm upgrade ... --set target_env=... when installing." .Values.target_env}}.api-policy-component'
        ports:
        - containerPort: 8080
        - containerPort: 8081
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5   
        resources: 
{{ toYaml .Values.resources | indent 12 }}